### ISSUE TITLE
Question Master settings -Logical Error

### ISSUE THREAD

**Issue by ginualex** [thomastom99/wc#3]
I am able to add an options repeatedly for a question
![bug](https://cloud.githubusercontent.com/assets/12725976/7954236/35c4764a-09eb-11e5-8441-b1716208cf23.jpg)
.

**Comment by thomastom99** [comment]
The Option should be different Right?

**Comment by thomastom99** [comment]
That Option 1 and two should be different contents..

**Comment by Revathyms** [comment]
What if someone try to add one option repeatedly(by mistake). We have to give some Warning wright? At present it doesnt shows any warning.

**Comment by thomastom99** [comment]
Yes It should show a Warning.. Sachin please fix this problem with an error message..

**Comment by thomastom99** [comment]
When you close the Bug.. Please give a small description about the bug fix .. how it is fixed etcif possible..

**Comment by sachin-jose** [comment]
The bug was actually a logical error. The user was able to add same option repeatedly for a question. I fixed the bug by checking all the options by using a list(added options to that list), and two loops to check the condition. Then i tested the page by checking all the possibilities. I hope the issue is fixed now.
